import { Bebas_Neue, Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  variable: "--Ubuntu",
  weight: ["300", "400", "500", "700"],
});

const bebas_neue = Bebas_Neue({
  subsets: ["latin"],
  variable: "--Bebas_Neue",
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} ${bebas_neue.variable}`}>
        {/* <Nav /> */}
        {children}
      </body>
    </html>
  );
}
